### ISSUE TITLE
%ForInIteratorPrototype% "is never directly accessible to ECMAScript code"

### ISSUE THREAD

**Issue by senocular** [tc39/proposal-get-intrinsic#14]
Will the "is never directly accessible to ECMAScript code" language in the spec need to change for intrinsics like this or should they be omitted from the values accessible through `getIntrinsic()`?

> The %ForInIteratorPrototype% object:
> ...
> * is never directly accessible to ECMAScript code.

https://tc39.es/ecma262/#sec-%foriniteratorprototype%-object

**Comment by ljharb** [comment]
Anything otherwise inaccessible would need to remain so, so thus one would need to be explicitly excluded. Thanks for the callout.
