### ISSUE TITLE
Open question: Have dedicated literals been considered?

### ISSUE THREAD

**Issue by celmaun** [tc39/proposal-get-intrinsic#9]
It will be a cat-and-mouse game trying to get hold of original intrinsics/`getIntrinstic` before someone else tampers them. So in my opinion this makes more sense as a syntax level thing, having `%xyz%` literals . i.e., 
`const SomeIntrinsic = %IntrinsicName%;`. This rules out those shenanigans entirely.

As a bonus/headache prevention, any invalid/unsupported `IntrinsicName` is a syntax error at parse time. Babel/transpilers will take care of providing intrinsics to legacy environments of course (as is tradition with all new syntax). Another bonus, transpilers are in the unique position to put in authentic references to those intrinsics.

`getIntrinsic('%xyz%')` is prone to typos if it fails silently on invalid names. We should strive for the language to be writeable without IDEs, TypeScript etc.. In good ol' text editors.

P.S: I have not checked if these dual percent sign literals will be in conflict with some other ES proposal. V8 uses the `%` prefix for internal method names, but that probably/hopefully won't conflict with percent sign on both ends.

**Comment by Salmatron** [comment]
Also, dedicated literals will likely have massive performance advantage over getIntrinsic function calls. Secondly, transpilers will have a hard time polyfilling if getIntrinsic takes dynamic values... (`getIntrinsic(someVariable)`).

**Comment by Salmatron** [comment]
Well, unless of course the transpiler is allowed to replace `globalThis.getIntrinsic` with a polyfilled version. Then back to square one above lol.

**Comment by ljharb** [comment]
They won’t be ever increasing - as supported browsers fall off the list, the number of intrinsics that need polyfilling will diminish.

An intrinsic is anything that exists before your code runs - including polyfills.
